//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_view_RevenueReport
    {
        public string StudentRunningNumber { get; set; }
        public string StudentID { get; set; }
        public System.DateTime InvDate { get; set; }
        public string InvNumber { get; set; }
        public decimal InvAmount { get; set; }
        public string StudentName { get; set; }
        public string BranchName { get; set; }
        public string CourseName { get; set; }
        public string BranchID { get; set; }
        public string CourseID { get; set; }
        public string BatchID { get; set; }
        public string BatchName { get; set; }
        public bool Active { get; set; }
        public int NetAmount { get; set; }
    }
}
