//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_view_Course
    {
        public string CourseID { get; set; }
        public string CourseName { get; set; }
        public bool Active { get; set; }
        public bool False { get; set; }
        public bool True { get; set; }
        public string Post { get; set; }
    }
}
