//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class debit_note_invoice
    {
        public Nullable<int> ID { get; set; }
        public string StudentRunningNumber { get; set; }
        public string StudentID { get; set; }
        public string TransactionType { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public double Amount { get; set; }
        public Nullable<decimal> AllocatedAmount { get; set; }
        public Nullable<bool> isAllocated { get; set; }
        public string EnterUser { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public bool SaveStatus { get; set; }
        public string PostUser { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public bool ForeignValue { get; set; }
        public string Currency { get; set; }
    }
}
