//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PERFECTIBSEntities : DbContext
    {
        public PERFECTIBSEntities()
            : base("name=PERFECTIBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccessLevelType> tblAccessLevelTypes { get; set; }
        public virtual DbSet<tblAgent> tblAgents { get; set; }
        public virtual DbSet<tblBankDetail> tblBankDetails { get; set; }
        public virtual DbSet<tblBankTransactionDetail> tblBankTransactionDetails { get; set; }
        public virtual DbSet<tblBussinessUnit> tblBussinessUnits { get; set; }
        public virtual DbSet<tblCauseOfLoss> tblCauseOfLosses { get; set; }
        public virtual DbSet<tblClaimPayment> tblClaimPayments { get; set; }
        public virtual DbSet<tblClaimPaymentMethod> tblClaimPaymentMethods { get; set; }
        public virtual DbSet<tblClaimRecHistory> tblClaimRecHistories { get; set; }
        public virtual DbSet<tblClaimRecPendingDoc> tblClaimRecPendingDocs { get; set; }
        public virtual DbSet<tblClaimRejectReason> tblClaimRejectReasons { get; set; }
        public virtual DbSet<tblClaimReOpenReason> tblClaimReOpenReasons { get; set; }
        public virtual DbSet<tblClientProperty> tblClientProperties { get; set; }
        public virtual DbSet<tblClientRequestInsSubClassScope> tblClientRequestInsSubClassScopes { get; set; }
        public virtual DbSet<tblClientRequestLine> tblClientRequestLines { get; set; }
        public virtual DbSet<tblCommisionStructureHeader> tblCommisionStructureHeaders { get; set; }
        public virtual DbSet<tblCommisionStructureLine> tblCommisionStructureLines { get; set; }
        public virtual DbSet<tblCommisionType> tblCommisionTypes { get; set; }
        public virtual DbSet<tblCommonInsScope> tblCommonInsScopes { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblCoverNote> tblCoverNotes { get; set; }
        public virtual DbSet<tblCurrency> tblCurrencies { get; set; }
        public virtual DbSet<tblDebitNote> tblDebitNotes { get; set; }
        public virtual DbSet<tblDesignation> tblDesignations { get; set; }
        public virtual DbSet<tblDocCategory> tblDocCategories { get; set; }
        public virtual DbSet<tblDocument> tblDocuments { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblFunction> tblFunctions { get; set; }
        public virtual DbSet<tblFunctionAccess> tblFunctionAccesses { get; set; }
        public virtual DbSet<tblFunctionType> tblFunctionTypes { get; set; }
        public virtual DbSet<tblInsClass> tblInsClasses { get; set; }
        public virtual DbSet<tblInsCompany> tblInsCompanies { get; set; }
        public virtual DbSet<tblInsSubClass> tblInsSubClasses { get; set; }
        public virtual DbSet<tblInternalPolicyNumSetup> tblInternalPolicyNumSetups { get; set; }
        public virtual DbSet<tblIntroducer> tblIntroducers { get; set; }
        public virtual DbSet<tblIntroducerBusinessUnit> tblIntroducerBusinessUnits { get; set; }
        public virtual DbSet<tblLoadingType> tblLoadingTypes { get; set; }
        public virtual DbSet<tblParentCompany> tblParentCompanies { get; set; }
        public virtual DbSet<tblPartnerMapping> tblPartnerMappings { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblPaymentType> tblPaymentTypes { get; set; }
        public virtual DbSet<tblPolicy> tblPolicies { get; set; }
        public virtual DbSet<tblPolicyCategory> tblPolicyCategories { get; set; }
        public virtual DbSet<tblPolicyDebitNote> tblPolicyDebitNotes { get; set; }
        public virtual DbSet<tblPolicyInfoPayment> tblPolicyInfoPayments { get; set; }
        public virtual DbSet<tblPolicyInformationBUPA> tblPolicyInformationBUPAs { get; set; }
        public virtual DbSet<tblPolicyInformationRecording> tblPolicyInformationRecordings { get; set; }
        public virtual DbSet<tblPolicyMemberDetail> tblPolicyMemberDetails { get; set; }
        public virtual DbSet<tblPolicyRenewalHistory> tblPolicyRenewalHistories { get; set; }
        public virtual DbSet<tblPremium> tblPremiums { get; set; }
        public virtual DbSet<tblQuotationDetailsInsCompanyHeader> tblQuotationDetailsInsCompanyHeaders { get; set; }
        public virtual DbSet<tblQuotationDetailsInsCompanyLine> tblQuotationDetailsInsCompanyLines { get; set; }
        public virtual DbSet<tblQuotationDetailsInsCompanyScope> tblQuotationDetailsInsCompanyScopes { get; set; }
        public virtual DbSet<tblQuotationLine> tblQuotationLines { get; set; }
        public virtual DbSet<tblQuotationRequestedInsCompany> tblQuotationRequestedInsCompanies { get; set; }
        public virtual DbSet<tblQuotationStatu> tblQuotationStatus { get; set; }
        public virtual DbSet<tblRateCategory> tblRateCategories { get; set; }
        public virtual DbSet<tblRequiredDocument> tblRequiredDocuments { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
        public virtual DbSet<tblTaxType> tblTaxTypes { get; set; }
        public virtual DbSet<tblTransactionType> tblTransactionTypes { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblFamilyDiscount> tblFamilyDiscounts { get; set; }
        public virtual DbSet<tblAccountHandler> tblAccountHandlers { get; set; }
        public virtual DbSet<tblComCommisionStructureLine> tblComCommisionStructureLine { get; set; }
        public virtual DbSet<tblInsComCommisionStructureHeader> tblInsComCommisionStructureHeader { get; set; }
        public virtual DbSet<tblDistrict> tblDistrict { get; set; }
        public virtual DbSet<tblClaimStatu> tblClaimStatus { get; set; }
        public virtual DbSet<tblInsClassType> tblInsClassTypes { get; set; }
        public virtual DbSet<tblYear> tblYears { get; set; }
        public virtual DbSet<tblClaimRecording> tblClaimRecordings { get; set; }
        public virtual DbSet<UploadedFile> UploadedFiles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SingaporeAdmission> SingaporeAdmissions { get; set; }
        public virtual DbSet<tblEndorsementCharge> tblEndorsementCharges { get; set; }
        public virtual DbSet<tblEndorsementInfo> tblEndorsementInfoes { get; set; }
        public virtual DbSet<SingaporeInvoice> SingaporeInvoices { get; set; }
        public virtual DbSet<tblPolicyCommisionPayment> tblPolicyCommisionPayment { get; set; }
        public virtual DbSet<tblPolicyCommisionPayment_New> tblPolicyCommisionPayment_New { get; set; }
        public virtual DbSet<tblPolicyInforCharge_New> tblPolicyInforCharge_New { get; set; }
        public virtual DbSet<tblJLT> tblJLT { get; set; }
        public virtual DbSet<tblWBN> tblWBN { get; set; }
        public virtual DbSet<tblTitle> tblTitle { get; set; }
        public virtual DbSet<tblHospitals> tblHospitals { get; set; }
        public virtual DbSet<tblScheme> tblScheme { get; set; }
        public virtual DbSet<tblCommissionFormat> tblCommissionFormat { get; set; }
        public virtual DbSet<tblGender> tblGender { get; set; }
        public virtual DbSet<tblRelationship> tblRelationship { get; set; }
        public virtual DbSet<tblDeductionsLine> tblDeductionsLine { get; set; }
        public virtual DbSet<tblCommissionFormatNew> tblCommissionFormatNews { get; set; }
        public virtual DbSet<tblCustomerQuotation> tblCustomerQuotations { get; set; }
        public virtual DbSet<tblChargeType> tblChargeTypes { get; set; }
        public virtual DbSet<tblClient> tblClients { get; set; }
        public virtual DbSet<tblPolicyInfoCharge> tblPolicyInfoCharges { get; set; }
        public virtual DbSet<tblAgeWisePremium> tblAgeWisePremium { get; set; }
        public virtual DbSet<tblPartner> tblPartners { get; set; }
        public virtual DbSet<tblDeductionType> tblDeductionTypes { get; set; }
        public virtual DbSet<tblPilotPremium> tblPilotPremiums { get; set; }
        public virtual DbSet<tblPremiumHolderType> tblPremiumHolderTypes { get; set; }
        public virtual DbSet<tblGrpFamilyDetail> tblGrpFamilyDetails { get; set; }
        public virtual DbSet<PatientAdmission> PatientAdmissions { get; set; }
        public virtual DbSet<tblFamilyMember> tblFamilyMembers { get; set; }
        public virtual DbSet<tblReceivedQuotation> tblReceivedQuotations { get; set; }
        public virtual DbSet<tblClientRequestHeader> tblClientRequestHeaders { get; set; }
        public virtual DbSet<tblDeduction> tblDeductions { get; set; }
        public virtual DbSet<tblQuotationHeader> tblQuotationHeaders { get; set; }
        public virtual DbSet<Admission_Singapore> Admission_Singapore { get; set; }
        public virtual DbSet<MemberStatu> MemberStatus { get; set; }
        public virtual DbSet<Trf_Bupa> Trf_Bupa { get; set; }
        public virtual DbSet<tblPilotPRM> tblPilotPRMs { get; set; }
        public virtual DbSet<tblClientRHistory> tblClientRHistories { get; set; }
        public virtual DbSet<tblClientRenewelRequestHeader> tblClientRenewelRequestHeaders { get; set; }
        public virtual DbSet<tblClientRewenelHistory> tblClientRewenelHistories { get; set; }
        public virtual DbSet<tblClientRnlRequestHeader> tblClientRnlRequestHeaders { get; set; }
        public virtual DbSet<tblFrequncyDetail> tblFrequncyDetails { get; set; }
        public virtual DbSet<tblTransactionDetail> tblTransactionDetails { get; set; }
    
        public virtual ObjectResult<sp_GetClientVSQuotation_Count_Result> sp_GetClientVSQuotation_Count()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetClientVSQuotation_Count_Result>("sp_GetClientVSQuotation_Count");
        }
    
        public virtual ObjectResult<spGetInsCompanyByClientRequestLine_Result> spGetInsCompanyByClientRequestLine(Nullable<int> clientRequestLineID)
        {
            var clientRequestLineIDParameter = clientRequestLineID.HasValue ?
                new ObjectParameter("ClientRequestLineID", clientRequestLineID) :
                new ObjectParameter("ClientRequestLineID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetInsCompanyByClientRequestLine_Result>("spGetInsCompanyByClientRequestLine", clientRequestLineIDParameter);
        }
    
        public virtual ObjectResult<spSearchChartedAccounts_Result> spSearchChartedAccounts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSearchChartedAccounts_Result>("spSearchChartedAccounts");
        }
    
        public virtual ObjectResult<spSearchClient_Result> spSearchClient(Nullable<int> businessUnitID, Nullable<int> homeCountryID, Nullable<int> residentCountryID)
        {
            var businessUnitIDParameter = businessUnitID.HasValue ?
                new ObjectParameter("BusinessUnitID", businessUnitID) :
                new ObjectParameter("BusinessUnitID", typeof(int));
    
            var homeCountryIDParameter = homeCountryID.HasValue ?
                new ObjectParameter("HomeCountryID", homeCountryID) :
                new ObjectParameter("HomeCountryID", typeof(int));
    
            var residentCountryIDParameter = residentCountryID.HasValue ?
                new ObjectParameter("ResidentCountryID", residentCountryID) :
                new ObjectParameter("ResidentCountryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSearchClient_Result>("spSearchClient", businessUnitIDParameter, homeCountryIDParameter, residentCountryIDParameter);
        }
    
        public virtual ObjectResult<spGetCommissionDetails_Result> spGetCommissionDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCommissionDetails_Result>("spGetCommissionDetails");
        }
    
        public virtual ObjectResult<spGetAllBupaPremiumClient_Result> spGetAllBupaPremiumClient()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAllBupaPremiumClient_Result>("spGetAllBupaPremiumClient");
        }
    }
}
