//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecturer_counselor_invoice
    {
        public int ID { get; set; }
        public string PayeeID { get; set; }
        public string PayeeType { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public double Amount { get; set; }
        public string EnterUser { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public bool SaveStatus { get; set; }
        public string PostUser { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public bool ForeignValue { get; set; }
        public string Currency { get; set; }
        public string BranchID { get; set; }
        public string BatchID { get; set; }
        public string CourseID { get; set; }
    }
}
