//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecturer_counselor_master_Log
    {
        public int LogID { get; set; }
        public string ID { get; set; }
        public string PayeeID { get; set; }
        public string PayeeName { get; set; }
        public string PayeeType { get; set; }
        public string PBSSID { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string EMail { get; set; }
        public string Active { get; set; }
        public string EnterUser { get; set; }
        public string EnterDate { get; set; }
        public System.DateTime LogDate { get; set; }
    }
}
