//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecturer_counselor_invoice_Log
    {
        public int LogID { get; set; }
        public string ID { get; set; }
        public string PayeeID { get; set; }
        public string PayeeType { get; set; }
        public string ReferenceNo { get; set; }
        public string TransactionDate { get; set; }
        public string Amount { get; set; }
        public string EnterUser { get; set; }
        public string EnterDate { get; set; }
        public string ForeignValue { get; set; }
        public string Currency { get; set; }
        public string BranchID { get; set; }
        public string BatchID { get; set; }
        public string CourseID { get; set; }
        public System.DateTime LogDate { get; set; }
    }
}
