//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<debit_note_invoice_Log> debit_note_invoice_Log { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<lecturer_counselor_invoice> lecturer_counselor_invoice { get; set; }
        public virtual DbSet<lecturer_counselor_invoice_Log> lecturer_counselor_invoice_Log { get; set; }
        public virtual DbSet<lecturer_counselor_master> lecturer_counselor_master { get; set; }
        public virtual DbSet<lecturer_counselor_master_Log> lecturer_counselor_master_Log { get; set; }
        public virtual DbSet<revenuerecognition_Log> revenuerecognition_Log { get; set; }
        public virtual DbSet<student_receivables_Log> student_receivables_Log { get; set; }
        public virtual DbSet<tbl_AccountMaster> tbl_AccountMaster { get; set; }
        public virtual DbSet<tbl_AccountMaster_Log> tbl_AccountMaster_Log { get; set; }
        public virtual DbSet<tbl_ActivityDetails> tbl_ActivityDetails { get; set; }
        public virtual DbSet<tbl_ActivityMaster> tbl_ActivityMaster { get; set; }
        public virtual DbSet<tbl_ActivityStatus> tbl_ActivityStatus { get; set; }
        public virtual DbSet<tbl_Batch> tbl_Batch { get; set; }
        public virtual DbSet<tbl_Branch> tbl_Branch { get; set; }
        public virtual DbSet<tbl_CodeFormat> tbl_CodeFormat { get; set; }
        public virtual DbSet<tbl_Course> tbl_Course { get; set; }
        public virtual DbSet<tbl_EmployeeMaster> tbl_EmployeeMaster { get; set; }
        public virtual DbSet<tbl_EmpRates> tbl_EmpRates { get; set; }
        public virtual DbSet<tbl_IntegrationTimes> tbl_IntegrationTimes { get; set; }
        public virtual DbSet<tbl_JobInvoices> tbl_JobInvoices { get; set; }
        public virtual DbSet<tbl_JobMaster> tbl_JobMaster { get; set; }
        public virtual DbSet<tbl_LecturerType> tbl_LecturerType { get; set; }
        public virtual DbSet<tbl_SalesOrders> tbl_SalesOrders { get; set; }
        public virtual DbSet<tbl_SalesOrders_Log> tbl_SalesOrders_Log { get; set; }
        public virtual DbSet<tbl_SalesOrders_Temp> tbl_SalesOrders_Temp { get; set; }
        public virtual DbSet<tbl_StudentInvoice> tbl_StudentInvoice { get; set; }
        public virtual DbSet<tbl_SupplierMaster> tbl_SupplierMaster { get; set; }
        public virtual DbSet<tbl_SupplierMaster_Log> tbl_SupplierMaster_Log { get; set; }
        public virtual DbSet<tbl_TrCodes> tbl_TrCodes { get; set; }
        public virtual DbSet<tblTrans_Supplier_BankGuarantee> tblTrans_Supplier_BankGuarantee { get; set; }
        public virtual DbSet<Test2> Test2 { get; set; }
        public virtual DbSet<debit_note_invoice> debit_note_invoice { get; set; }
        public virtual DbSet<MSreplication_options> MSreplication_options { get; set; }
        public virtual DbSet<revenuerecognition> revenuerecognitions { get; set; }
        public virtual DbSet<spt_fallback_db> spt_fallback_db { get; set; }
        public virtual DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
        public virtual DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
        public virtual DbSet<spt_monitor> spt_monitor { get; set; }
        public virtual DbSet<student_receivables> student_receivables { get; set; }
        public virtual DbSet<tbl_BOQDetails> tbl_BOQDetails { get; set; }
        public virtual DbSet<tbl_Login> tbl_Login { get; set; }
    }
}
