//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAdmission
    {
        public int PatientAdmissionId { get; set; }
        public string ReferenceNo { get; set; }
        public string PatientName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PassportNumber { get; set; }
        public string Scheme { get; set; }
        public Nullable<System.DateTime> InceptionDate { get; set; }
        public Nullable<decimal> Deductible { get; set; }
        public Nullable<decimal> DeductibleForTheYear { get; set; }
        public Nullable<decimal> Exclusions { get; set; }
        public string Hospital { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public string BHTNumber { get; set; }
        public string Illness { get; set; }
        public string ConsultantName { get; set; }
        public string InformedBy { get; set; }
        public Nullable<decimal> GOPAmount { get; set; }
        public string GOPConfirmedBy { get; set; }
        public Nullable<System.DateTime> GOPIssuedDate { get; set; }
        public Nullable<decimal> ExtendedGOP { get; set; }
        public string HandledBy { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public Nullable<decimal> ConsultantFee { get; set; }
        public Nullable<System.DateTime> FinalBillReceivedDate { get; set; }
        public Nullable<decimal> FinalBillGivenToSGS { get; set; }
        public Nullable<decimal> AVIVADCSClaims { get; set; }
        public Nullable<System.DateTime> ClaimSettledDate { get; set; }
        public Nullable<decimal> ReferalFee { get; set; }
        public Nullable<System.DateTime> ReferalFeeReceivedDate { get; set; }
        public string ReferalFeeReceivedBank { get; set; }
        public string ReferalFeeReceivedChequeNo { get; set; }
        public string ReferalFeeReceivedTTNo { get; set; }
        public Nullable<decimal> PaymentGivenToAccount { get; set; }
        public string Remark { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> PremiumHolderType { get; set; }
        public Nullable<decimal> IncurredAmount { get; set; }
        public Nullable<System.DateTime> ClaimDocumentReceivedDate { get; set; }
        public Nullable<System.DateTime> ClaimDocumentsEmailedDate { get; set; }
        public Nullable<System.DateTime> PaymentAdviceReceviedDate { get; set; }
        public Nullable<System.DateTime> PaymentAdviceEmailedDate { get; set; }
        public Nullable<decimal> TotalAmountPaid { get; set; }
        public Nullable<int> CurrencyType { get; set; }
        public Nullable<System.DateTime> OriginalDocumentscourieredDate { get; set; }
        public string AirwayBillNo { get; set; }
        public string ExtraText1 { get; set; }
        public string ExtraText2 { get; set; }
        public Nullable<int> ExtraInt1 { get; set; }
        public Nullable<int> ExtraInt2 { get; set; }
        public Nullable<decimal> ExtraFloat1 { get; set; }
        public Nullable<decimal> ExtraFloat2 { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> BUID { get; set; }
        public Nullable<int> CurrancyID { get; set; }
        public string CurrancyCode { get; set; }
        public string MembershipID { get; set; }
    }
}
