//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class revenuerecognition
    {
        public Nullable<int> ID { get; set; }
        public string StudentRunningNumber { get; set; }
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public string BranchID { get; set; }
        public string BranchName { get; set; }
        public string CourseID { get; set; }
        public string CourseName { get; set; }
        public string BatchID { get; set; }
        public string BatchName { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string EMail { get; set; }
        public int CourseDuration { get; set; }
        public int NetAmount { get; set; }
        public int BatchStartMonth { get; set; }
        public int BatchStartYear { get; set; }
        public int StudentStartMonth { get; set; }
        public int StudentStartYear { get; set; }
        public bool RevesalFlag { get; set; }
        public Nullable<System.DateTime> ReversalDate { get; set; }
        public string PrevStudentID { get; set; }
        public string EnterUser { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public bool SaveStatus { get; set; }
        public string PostUser { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public bool Active { get; set; }
        public bool ForeignNetValue { get; set; }
        public string Currency { get; set; }
        public bool Oustanding { get; set; }
        public int OustandingAmount { get; set; }
        public string SageStudentID { get; set; }
        public Nullable<int> InvoicedPeriod { get; set; }
        public Nullable<bool> isForeginCode { get; set; }
        public Nullable<System.DateTime> ForeginPostDate { get; set; }
        public string Univercity_Fee { get; set; }
        public string Pay_Amount_to_univercity { get; set; }
        public string Univercity_Fee_Currency_Coad { get; set; }
    }
}
