//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class revenuerecognition_Log
    {
        public int LogID { get; set; }
        public string ID { get; set; }
        public string StudentRunningNumber { get; set; }
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public string BranchID { get; set; }
        public string BranchName { get; set; }
        public string CourseID { get; set; }
        public string CourseName { get; set; }
        public string BatchID { get; set; }
        public string BatchName { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string EMail { get; set; }
        public string CourseDuration { get; set; }
        public string NetAmount { get; set; }
        public string BatchStartMonth { get; set; }
        public string BatchStartYear { get; set; }
        public string StudentStartMonth { get; set; }
        public string StudentStartYear { get; set; }
        public string RevesalFlag { get; set; }
        public string ReversalDate { get; set; }
        public string PrevStudentID { get; set; }
        public string EnterUser { get; set; }
        public string EnterDate { get; set; }
        public string Active { get; set; }
        public string ForeignNetValue { get; set; }
        public string Currency { get; set; }
        public string Oustanding { get; set; }
        public string OustandingAmount { get; set; }
        public string Univercity_Fee { get; set; }
        public string Pay_Amount_to_univercity { get; set; }
        public string Univercity_Fee_Currency_Coad { get; set; }
        public System.DateTime LogDate { get; set; }
    }
}
