//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingaporeInvoice
    {
        public long SingaporeInvoiceId { get; set; }
        public string ReferenceNo { get; set; }
        public string Terms { get; set; }
        public string Customerid { get; set; }
        public string ClaimsAssessor { get; set; }
        public string MembershipNo { get; set; }
        public string BeneficiaryName { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string BankBrach { get; set; }
        public string SwiftCode { get; set; }
        public string BankCode { get; set; }
    }
}
