//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingaporeAdmission
    {
        public int SingaporeAdmissionId { get; set; }
        public string PatientName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string ReferenceNo { get; set; }
        public string PassportNumber { get; set; }
        public string Scheme { get; set; }
        public System.DateTime InceptionDate { get; set; }
        public decimal Deductible { get; set; }
        public decimal DeductibleForTheYear { get; set; }
        public decimal Exclusions { get; set; }
        public string Hospital { get; set; }
        public System.DateTime InimatedDate { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public System.DateTime DischargeDate { get; set; }
        public string CaseNumber { get; set; }
        public string Illness { get; set; }
        public string ConsultantName { get; set; }
        public string InformedBy { get; set; }
        public decimal GOPAmount { get; set; }
        public decimal ExtendedGOP { get; set; }
        public decimal FinalAmount { get; set; }
        public decimal ConsultantFee { get; set; }
        public decimal ReferalFee { get; set; }
        public System.DateTime ReferalFeeReceivedDate { get; set; }
        public System.DateTime FinalBillReceivedDate { get; set; }
        public string ReferalFeeReceivedTTNo { get; set; }
        public decimal PaymentGivenToAccount { get; set; }
        public string Remark { get; set; }
        public string CMAInvoiceNumber { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> DependantID { get; set; }
        public Nullable<decimal> FinalBill { get; set; }
        public Nullable<System.DateTime> ExtendedGOPDate { get; set; }
    }
}
