//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CodeFormat
    {
        public int ID { get; set; }
        public string Prefix { get; set; }
        public decimal Counter { get; set; }
        public string DefaultValue { get; set; }
        public decimal Increment { get; set; }
    }
}
