//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login
    {
        public string UserID { get; set; }
        public string PassWord { get; set; }
        public string UserLevel { get; set; }
        public Nullable<bool> LoginStatus { get; set; }
        public string Machine { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
