//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesOrders_Log
    {
        public int AutoID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string GDC { get; set; }
        public string TransType { get; set; }
        public string AccountNo_GLCode { get; set; }
        public string ContraAccount { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AllocatedAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TaxAllocated { get; set; }
        public string OpenItemType { get; set; }
        public Nullable<bool> isForeginCode { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string CurrencyCode { get; set; }
        public string EnterUser { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<bool> SaveStatus { get; set; }
        public string PostUser { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string Mode { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
