//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentInvoice
    {
        public int ID { get; set; }
        public string InvNumber { get; set; }
        public string StudentRunningNumber { get; set; }
        public string StudentID { get; set; }
        public System.DateTime InvDate { get; set; }
        public string CourseID { get; set; }
        public string BatchID { get; set; }
        public string BranchID { get; set; }
        public decimal InvAmount { get; set; }
        public bool SaveStatus { get; set; }
        public string PostUser { get; set; }
        public System.DateTime PostDate { get; set; }
        public decimal AllocateAmount { get; set; }
        public bool isAllocated { get; set; }
    }
}
