//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Branch
    {
        public int ID { get; set; }
        public string BranchID { get; set; }
        public string BranchName { get; set; }
        public Nullable<bool> Active { get; set; }
        public bool SaveStatus { get; set; }
    }
}
