//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountMaster_Log
    {
        public int AutoID { get; set; }
        public Nullable<int> ID { get; set; }
        public string Account { get; set; }
        public string AccDescription { get; set; }
        public string AccType { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> isEdit { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<bool> PostStatus { get; set; }
        public string Mode { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
