//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountHandler
    {
        public int AccountHandlerID { get; set; }
        public string AccountHandlerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<double> ExtraFloat1 { get; set; }
        public Nullable<double> ExtraFloat2 { get; set; }
        public Nullable<double> ExtraFloat3 { get; set; }
        public string AccountHandlerCode { get; set; }
        public string AccountHandlerType { get; set; }
        public string AccountHandlerNIC { get; set; }
        public string ExtraText1 { get; set; }
        public string ExtraText2 { get; set; }
        public string ExtraText3 { get; set; }
        public string AgentBRNo { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
