//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommonInsScope
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCommonInsScope()
        {
            this.tblClientRequestInsSubClassScopes = new HashSet<tblClientRequestInsSubClassScope>();
        }
    
        public int CommonInsScopeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsClassID { get; set; }
        public Nullable<int> InsSubClassID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClientRequestInsSubClassScope> tblClientRequestInsSubClassScopes { get; set; }
        public virtual tblInsClass tblInsClass { get; set; }
        public virtual tblInsSubClass tblInsSubClass { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
