//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommisionStructureHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCommisionStructureHeader()
        {
            this.tblCommisionStructureLines = new HashSet<tblCommisionStructureLine>();
        }
    
        public int ComStructID { get; set; }
        public string ComStructName { get; set; }
        public string ConStructCode { get; set; }
        public Nullable<int> BUID { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public Nullable<int> InsCompanyID { get; set; }
        public Nullable<int> InsClassID { get; set; }
        public Nullable<int> InsSubClassID { get; set; }
        public Nullable<double> PremiumRate { get; set; }
        public Nullable<double> SRCCRate { get; set; }
        public Nullable<double> TCRate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual tblBussinessUnit tblBussinessUnit { get; set; }
        public virtual tblInsClass tblInsClass { get; set; }
        public virtual tblInsCompany tblInsCompany { get; set; }
        public virtual tblInsSubClass tblInsSubClass { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCommisionStructureLine> tblCommisionStructureLines { get; set; }
        public virtual tblPartner tblPartner { get; set; }
    }
}
