//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClaimRecording
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClaimRecording()
        {
            this.tblClaimPayments = new HashSet<tblClaimPayment>();
            this.tblClaimRecHistories = new HashSet<tblClaimRecHistory>();
            this.tblClaimRecPendingDocs = new HashSet<tblClaimRecPendingDoc>();
        }
    
        public int ClaimRecordingID { get; set; }
        public Nullable<int> PolicyInfoRecID { get; set; }
        public string ClaimNo { get; set; }
        public Nullable<System.DateTime> DateOfLoss { get; set; }
        public Nullable<System.DateTime> DateOfIntimation { get; set; }
        public string CauseOfLoss { get; set; }
        public string DamageDescription { get; set; }
        public Nullable<decimal> AmountClaimed { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string FileReferenceNo { get; set; }
        public string FilePath { get; set; }
        public string PaymentPendingReason { get; set; }
        public string WithdrawReason { get; set; }
        public bool IsOpened { get; set; }
        public bool IsRejected { get; set; }
        public bool IsWithdrawn { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DischargedDate { get; set; }
        public Nullable<System.DateTime> ClaimDocumentsReceivedDate { get; set; }
        public Nullable<System.DateTime> ClaimDocumentsEmailedDate { get; set; }
        public Nullable<System.DateTime> PaymentAdviceReceviedDate { get; set; }
        public Nullable<System.DateTime> PaymentAdviceEmailedDate { get; set; }
        public Nullable<System.DateTime> OriginalDocumentscourieredDate { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Year { get; set; }
        public string FileName { get; set; }
        public string ClaimentInfo { get; set; }
        public string Insurer { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<decimal> PolicyExcess { get; set; }
        public Nullable<int> InsClass { get; set; }
        public Nullable<int> InsClassTypes { get; set; }
        public Nullable<int> ClaimStatus { get; set; }
        public string ChequeDetails { get; set; }
        public string RejectedReason { get; set; }
        public string ContactPersonDetails { get; set; }
        public string Other { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public Nullable<int> ClaimPaidStatus { get; set; }
        public Nullable<System.DateTime> DateOfOpen { get; set; }
        public Nullable<System.DateTime> DateOfWithdraw { get; set; }
        public Nullable<System.DateTime> DateOfReject { get; set; }
        public string ExtraText1 { get; set; }
        public string ExtraText2 { get; set; }
        public string ExtraText3 { get; set; }
        public Nullable<int> ExtraInt1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimPayment> tblClaimPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimRecHistory> tblClaimRecHistories { get; set; }
        public virtual tblPolicyInformationRecording tblPolicyInformationRecording { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimRecPendingDoc> tblClaimRecPendingDocs { get; set; }
    }
}
