//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientRHistory
    {
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientAddress { get; set; }
        public string NIC { get; set; }
        public string ContactNo { get; set; }
        public string FixedLine { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PPID { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public Nullable<decimal> FamilyDiscount { get; set; }
        public string AdditionalNote { get; set; }
        public Nullable<int> HomeCountryID { get; set; }
        public Nullable<int> ResidentCountryID { get; set; }
        public Nullable<int> BUID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Other { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> Province { get; set; }
        public string FileNo { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public string BRNo { get; set; }
        public Nullable<int> TitleID { get; set; }
        public Nullable<int> ExtraInt { get; set; }
        public Nullable<int> ExtraInt1 { get; set; }
        public Nullable<decimal> ExtraFloat { get; set; }
        public string ExtraText { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string PremiumAccept { get; set; }
    }
}
