//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommissionFormatNew
    {
        public string RefNo { get; set; }
        public string RecordID { get; set; }
        public string Name { get; set; }
        public string PolicyNo { get; set; }
        public string TaxInvoiceNumber { get; set; }
        public string VehicleNumber { get; set; }
        public string InsuranceIssueDate { get; set; }
        public string pre_basic { get; set; }
        public string pre_SRCC { get; set; }
        public string prm_TC { get; set; }
        public string Rcomm { get; set; }
        public string Advice { get; set; }
        public string Insurer { get; set; }
    }
}
