//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeductionsLine
    {
        public int DeductionID { get; set; }
        public string PremiumHolder { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<decimal> LodingRate { get; set; }
        public Nullable<decimal> DeductionRate { get; set; }
        public Nullable<decimal> NetPremium { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> FamilyMemberID { get; set; }
        public Nullable<int> GroupFamilyMemberID { get; set; }
    }
}
