//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeduction
    {
        public int DeductionID { get; set; }
        public string PremiumHolder { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<decimal> LodingRate { get; set; }
        public Nullable<decimal> DeductionRate { get; set; }
        public Nullable<decimal> NetPremium { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> FamilyMemberID { get; set; }
        public string Deductibles { get; set; }
        public string ExtraText1 { get; set; }
        public Nullable<int> GroupFamilyMemberID { get; set; }
        public Nullable<int> PremiumID { get; set; }
        public Nullable<int> DeductionType { get; set; }
        public Nullable<decimal> DeductionAmount { get; set; }
        public string Exclusion { get; set; }
        public Nullable<int> BusinessUnit { get; set; }
        public string DeductionRemarks { get; set; }
        public string OptionalAmount { get; set; }
        public Nullable<decimal> LoadingAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> PremiumHolderType { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string MI { get; set; }
        public string FrequncyID { get; set; }
        public string FrequncyDID { get; set; }
        public string SeqNo { get; set; }
        public string SeqSubNo { get; set; }
        public string SNo { get; set; }
    
        public virtual tblClient tblClient { get; set; }
    }
}
