//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFamilyMember
    {
        public int FamilyMemberID { get; set; }
        public string MemberName { get; set; }
        public Nullable<System.DateTime> MemberDOB { get; set; }
        public string NICNo { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string MembershipID { get; set; }
        public Nullable<int> CountryOfResident { get; set; }
        public Nullable<int> HomeCountry { get; set; }
        public Nullable<int> RelationShipID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> Title { get; set; }
        public string MemberOtherName { get; set; }
        public Nullable<System.DateTime> InceptionDate { get; set; }
        public string ExtraText1 { get; set; }
        public string ExtraText2 { get; set; }
        public Nullable<int> ExtraInt1 { get; set; }
        public Nullable<int> ExtraInt2 { get; set; }
        public string premiumID { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string OptionalCover { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<double> Exclusions { get; set; }
        public string Exclu { get; set; }
        public string FrequncyID { get; set; }
        public string FrequncyDID { get; set; }
        public string SeqNo { get; set; }
        public string SeqSubNo { get; set; }
    
        public virtual tblClient tblClient { get; set; }
    }
}
