//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFunction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFunction()
        {
            this.tblFunctionAccesses = new HashSet<tblFunctionAccess>();
        }
    
        public int FunctionID { get; set; }
        public int FunctionTypeID { get; set; }
        public int FunctionNumber { get; set; }
        public string FunctionName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
    
        public virtual tblFunctionType tblFunctionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFunctionAccess> tblFunctionAccesses { get; set; }
    }
}
