//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrpFamilyDetail
    {
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public Nullable<System.DateTime> MemberDOB { get; set; }
        public string MemberNIC { get; set; }
        public string MemberContact { get; set; }
        public Nullable<int> FamilyMemberID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string MembershipID { get; set; }
        public Nullable<int> MemberCountryID { get; set; }
        public Nullable<System.DateTime> InceptionDate { get; set; }
        public Nullable<int> premiumID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string ExtraText1 { get; set; }
        public string ExtraText2 { get; set; }
        public Nullable<int> ExtraInt1 { get; set; }
        public Nullable<int> ExtraInt2 { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<int> RelationShipID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public Nullable<int> MemberOtherName { get; set; }
        public Nullable<int> MemberResCountryID { get; set; }
        public Nullable<double> Exclusions { get; set; }
        public string OptionalCovers { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string Exclu { get; set; }
        public string FrequncyID { get; set; }
        public string FrequncyDID { get; set; }
        public string SeqNo { get; set; }
        public string SeqSubNo { get; set; }
    }
}
