//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInsClassType
    {
        public int InsClassTypeID { get; set; }
        public Nullable<int> InsClass { get; set; }
        public string InsClassTypeDes { get; set; }
        public Nullable<int> BUID { get; set; }
    }
}
