//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyRenewalHistory
    {
        public int PolicyRenewalHistoryID { get; set; }
        public Nullable<int> PolicyInfoRecID { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public bool IsSent { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Agent { get; set; }
        public Nullable<int> Executive { get; set; }
        public Nullable<bool> IsRenewal { get; set; }
        public Nullable<System.DateTime> RenewalStartDate { get; set; }
        public Nullable<System.DateTime> RenewalEndDate { get; set; }
    
        public virtual tblPolicyInformationRecording tblPolicyInformationRecording { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
