//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyMemberDetail
    {
        public int PolicyMemberID { get; set; }
        public string PolicyMemberName { get; set; }
        public Nullable<System.DateTime> PolicyMemberJoinDate { get; set; }
        public Nullable<System.DateTime> PolicyMemberDOB { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual tblClient tblClient { get; set; }
    }
}
