//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyDebitNote
    {
        public int PolicyDebitNoteID { get; set; }
        public Nullable<int> PolicyInfoPaymentID { get; set; }
        public Nullable<int> DebitNoteID { get; set; }
        public Nullable<int> PaymentID { get; set; }
    
        public virtual tblDebitNote tblDebitNote { get; set; }
        public virtual tblPayment tblPayment { get; set; }
        public virtual tblPolicyInfoPayment tblPolicyInfoPayment { get; set; }
    }
}
