//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyInformationRecording
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPolicyInformationRecording()
        {
            this.tblPolicyInfoPayments = new HashSet<tblPolicyInfoPayment>();
            this.tblPolicyRenewalHistories = new HashSet<tblPolicyRenewalHistory>();
            this.tblClaimRecordings = new HashSet<tblClaimRecording>();
            this.tblPolicyCommisionPayment = new HashSet<tblPolicyCommisionPayment>();
        }
    
        public int PolicyInfoRecID { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<int> QuotationHeaderID { get; set; }
        public Nullable<int> QuotationDetailsInsCompanyLineID { get; set; }
        public Nullable<decimal> SumAssured { get; set; }
        public Nullable<int> SumAssuredCurrencyTypeID { get; set; }
        public Nullable<decimal> PremiumIncludingTax { get; set; }
        public Nullable<int> PremiumIncludingTaxCurrencyTypeID { get; set; }
        public Nullable<System.DateTime> PeriodOfCoverFromDate { get; set; }
        public Nullable<System.DateTime> PeriodOfCoverToDate { get; set; }
        public Nullable<decimal> NonCommissionPremium { get; set; }
        public Nullable<decimal> GrossPremium { get; set; }
        public string OtherExcessDescription { get; set; }
        public Nullable<decimal> OtherExcessAmount { get; set; }
        public string TaxInvoiceNumber { get; set; }
        public Nullable<decimal> TotalCommission { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> CommissionStructureHeaderID { get; set; }
        public string FileNumber { get; set; }
        public Nullable<int> AccountExecutiveID { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<int> IntroducerID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> InuranceCompanyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<System.DateTime> PolicyRequestedDate { get; set; }
        public Nullable<int> InsClassId { get; set; }
        public Nullable<int> InsSubClassId { get; set; }
        public Nullable<bool> IsLapse { get; set; }
        public string LapseRemark { get; set; }
    
        public virtual tblCurrency tblCurrency { get; set; }
        public virtual tblCurrency tblCurrency1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyInfoPayment> tblPolicyInfoPayments { get; set; }
        public virtual tblQuotationDetailsInsCompanyLine tblQuotationDetailsInsCompanyLine { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyRenewalHistory> tblPolicyRenewalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimRecording> tblClaimRecordings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyCommisionPayment> tblPolicyCommisionPayment { get; set; }
        public virtual tblQuotationHeader tblQuotationHeader { get; set; }
    }
}
