//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPremium
    {
        public int PremiumID { get; set; }
        public string PremiumName { get; set; }
        public string PremiumCode { get; set; }
        public Nullable<int> BUID { get; set; }
    }
}
