//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyCommisionPayment
    {
        public int PolicyCommisionPaymentID { get; set; }
        public Nullable<int> PolicyInfoRecID { get; set; }
        public Nullable<int> ComStructLineID { get; set; }
        public Nullable<int> CommisionTypeID { get; set; }
        public Nullable<decimal> CommisionValue { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblCommisionStructureLine tblCommisionStructureLine { get; set; }
        public virtual tblCommisionType tblCommisionType { get; set; }
        public virtual tblPolicyInformationRecording tblPolicyInformationRecording { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
