//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyInformationBUPA
    {
        public int PolicyInfoID { get; set; }
        public string Premium { get; set; }
        public string MemberID { get; set; }
        public Nullable<int> PolicyMethod { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual tblClient tblClient { get; set; }
    }
}
