//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotationHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuotationHeader()
        {
            this.tblCoverNotes = new HashSet<tblCoverNote>();
            this.tblPolicyInformationRecordings = new HashSet<tblPolicyInformationRecording>();
            this.tblQuotationLines = new HashSet<tblQuotationLine>();
        }
    
        public int QuotationHeaderID { get; set; }
        public Nullable<int> ClientRequestHeaderID { get; set; }
        public bool Status { get; set; }
        public string QuotationStatusCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Other { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<bool> IsReceived { get; set; }
    
        public virtual tblClientRequestHeader tblClientRequestHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCoverNote> tblCoverNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyInformationRecording> tblPolicyInformationRecordings { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationLine> tblQuotationLines { get; set; }
    }
}
