//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotationDetailsInsCompanyLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuotationDetailsInsCompanyLine()
        {
            this.tblPolicyInformationRecordings = new HashSet<tblPolicyInformationRecording>();
            this.tblQuotationDetailsInsCompanyScopes = new HashSet<tblQuotationDetailsInsCompanyScope>();
        }
    
        public int QuotationDetailsInsCompanyLineID { get; set; }
        public Nullable<int> QuotationDetailsInsCompanyHeaderID { get; set; }
        public Nullable<int> InsSubClassID { get; set; }
        public Nullable<decimal> SumInsured { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblInsSubClass tblInsSubClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyInformationRecording> tblPolicyInformationRecordings { get; set; }
        public virtual tblQuotationDetailsInsCompanyHeader tblQuotationDetailsInsCompanyHeader { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationDetailsInsCompanyScope> tblQuotationDetailsInsCompanyScopes { get; set; }
    }
}
