//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotationDetailsInsCompanyHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuotationDetailsInsCompanyHeader()
        {
            this.tblQuotationDetailsInsCompanyLines = new HashSet<tblQuotationDetailsInsCompanyLine>();
        }
    
        public int QuotationDetailsInsCompanyHeaderID { get; set; }
        public Nullable<int> QuotationRequestedInsCompanyID { get; set; }
        public Nullable<double> PremiumIncludingTax { get; set; }
        public string ExcessDescription { get; set; }
        public Nullable<decimal> ExcessAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblQuotationRequestedInsCompany tblQuotationRequestedInsCompany { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationDetailsInsCompanyLine> tblQuotationDetailsInsCompanyLines { get; set; }
    }
}
