//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotationRequestedInsCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuotationRequestedInsCompany()
        {
            this.tblQuotationDetailsInsCompanyHeaders = new HashSet<tblQuotationDetailsInsCompanyHeader>();
        }
    
        public int QuotationRequestedInsCompanyID { get; set; }
        public Nullable<int> QuotationLineID { get; set; }
        public Nullable<int> InsCompanyID { get; set; }
        public bool Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblInsCompany tblInsCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationDetailsInsCompanyHeader> tblQuotationDetailsInsCompanyHeaders { get; set; }
        public virtual tblQuotationLine tblQuotationLine { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
