//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotationLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuotationLine()
        {
            this.tblQuotationRequestedInsCompanies = new HashSet<tblQuotationRequestedInsCompany>();
        }
    
        public int QuotationLineID { get; set; }
        public Nullable<int> QuotationHeaderID { get; set; }
        public Nullable<int> InsClassID { get; set; }
        public Nullable<int> InsSubClassID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Other { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<bool> IsRequested { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedFilePath { get; set; }
        public string ReceivedFileName { get; set; }
        public string ReceivedUser { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public string SelectedUser { get; set; }
    
        public virtual tblInsClass tblInsClass { get; set; }
        public virtual tblInsSubClass tblInsSubClass { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationRequestedInsCompany> tblQuotationRequestedInsCompanies { get; set; }
        public virtual tblQuotationHeader tblQuotationHeader { get; set; }
    }
}
