//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceivedQuotation
    {
        public int ReceivedQuotionId { get; set; }
        public int QuotationRequestHeaderId { get; set; }
        public Nullable<int> QuotationRequestDetailId { get; set; }
        public int CompanyId { get; set; }
        public int ClassId { get; set; }
        public int SubClassId { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedUser { get; set; }
    }
}
