//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScheme
    {
        public int SchemeID { get; set; }
        public Nullable<int> PremiumID { get; set; }
        public string SchemeCat { get; set; }
        public Nullable<decimal> SchemePremium { get; set; }
    }
}
