//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransactionDetail
    {
        public int Id { get; set; }
        public string CurrencyCode { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string AgentCode { get; set; }
        public bool IsTransfer { get; set; }
    }
}
