//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrans_Supplier_BankGuarantee
    {
        public int ID { get; set; }
        public string TransactionID { get; set; }
        public string DebitAccNumber { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAccNo { get; set; }
        public string SupplierBankCode { get; set; }
        public string SupplierBranchCode { get; set; }
        public string TransactionCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
        public string SupplierMobile { get; set; }
        public string SupplierEmail { get; set; }
        public string ProductType { get; set; }
        public string SWIFTCode { get; set; }
        public Nullable<bool> IsGenerateFiles { get; set; }
        public Nullable<System.DateTime> GenerateTime { get; set; }
        public string GenerateUser { get; set; }
        public string TestFileName { get; set; }
        public string BankName { get; set; }
        public Nullable<int> SalesOrderTblID { get; set; }
    }
}
