//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblAgents = new HashSet<tblAgent>();
            this.tblAgents1 = new HashSet<tblAgent>();
            this.tblBussinessUnits = new HashSet<tblBussinessUnit>();
            this.tblBussinessUnits1 = new HashSet<tblBussinessUnit>();
            this.tblCauseOfLosses = new HashSet<tblCauseOfLoss>();
            this.tblCauseOfLosses1 = new HashSet<tblCauseOfLoss>();
            this.tblClaimPayments = new HashSet<tblClaimPayment>();
            this.tblClaimPayments1 = new HashSet<tblClaimPayment>();
            this.tblClaimPaymentMethods = new HashSet<tblClaimPaymentMethod>();
            this.tblClaimPaymentMethods1 = new HashSet<tblClaimPaymentMethod>();
            this.tblClaimRecHistories = new HashSet<tblClaimRecHistory>();
            this.tblClaimRecHistories1 = new HashSet<tblClaimRecHistory>();
            this.tblClaimRecPendingDocs = new HashSet<tblClaimRecPendingDoc>();
            this.tblClaimRecPendingDocs1 = new HashSet<tblClaimRecPendingDoc>();
            this.tblClaimRejectReasons = new HashSet<tblClaimRejectReason>();
            this.tblClaimRejectReasons1 = new HashSet<tblClaimRejectReason>();
            this.tblClaimReOpenReasons = new HashSet<tblClaimReOpenReason>();
            this.tblClaimReOpenReasons1 = new HashSet<tblClaimReOpenReason>();
            this.tblClientProperties = new HashSet<tblClientProperty>();
            this.tblClientProperties1 = new HashSet<tblClientProperty>();
            this.tblClientRequestInsSubClassScopes = new HashSet<tblClientRequestInsSubClassScope>();
            this.tblClientRequestInsSubClassScopes1 = new HashSet<tblClientRequestInsSubClassScope>();
            this.tblClientRequestLines = new HashSet<tblClientRequestLine>();
            this.tblClientRequestLines1 = new HashSet<tblClientRequestLine>();
            this.tblCommisionStructureHeaders = new HashSet<tblCommisionStructureHeader>();
            this.tblCommisionStructureHeaders1 = new HashSet<tblCommisionStructureHeader>();
            this.tblCommisionStructureLines = new HashSet<tblCommisionStructureLine>();
            this.tblCommisionStructureLines1 = new HashSet<tblCommisionStructureLine>();
            this.tblCommisionTypes = new HashSet<tblCommisionType>();
            this.tblCommisionTypes1 = new HashSet<tblCommisionType>();
            this.tblCommonInsScopes = new HashSet<tblCommonInsScope>();
            this.tblCommonInsScopes1 = new HashSet<tblCommonInsScope>();
            this.tblCompanies = new HashSet<tblCompany>();
            this.tblCompanies1 = new HashSet<tblCompany>();
            this.tblCoverNotes = new HashSet<tblCoverNote>();
            this.tblCoverNotes1 = new HashSet<tblCoverNote>();
            this.tblDebitNotes = new HashSet<tblDebitNote>();
            this.tblDebitNotes1 = new HashSet<tblDebitNote>();
            this.tblDesignations = new HashSet<tblDesignation>();
            this.tblDesignations1 = new HashSet<tblDesignation>();
            this.tblDocCategories = new HashSet<tblDocCategory>();
            this.tblDocCategories1 = new HashSet<tblDocCategory>();
            this.tblDocuments = new HashSet<tblDocument>();
            this.tblDocuments1 = new HashSet<tblDocument>();
            this.tblEmployees = new HashSet<tblEmployee>();
            this.tblEmployees1 = new HashSet<tblEmployee>();
            this.tblInsClasses = new HashSet<tblInsClass>();
            this.tblInsClasses1 = new HashSet<tblInsClass>();
            this.tblInsCompanies = new HashSet<tblInsCompany>();
            this.tblInsCompanies1 = new HashSet<tblInsCompany>();
            this.tblInsSubClasses = new HashSet<tblInsSubClass>();
            this.tblInsSubClasses1 = new HashSet<tblInsSubClass>();
            this.tblInternalPolicyNumSetups = new HashSet<tblInternalPolicyNumSetup>();
            this.tblInternalPolicyNumSetups1 = new HashSet<tblInternalPolicyNumSetup>();
            this.tblIntroducers = new HashSet<tblIntroducer>();
            this.tblIntroducers1 = new HashSet<tblIntroducer>();
            this.tblLoadingTypes = new HashSet<tblLoadingType>();
            this.tblLoadingTypes1 = new HashSet<tblLoadingType>();
            this.tblParentCompanies = new HashSet<tblParentCompany>();
            this.tblParentCompanies1 = new HashSet<tblParentCompany>();
            this.tblPartnerMappings = new HashSet<tblPartnerMapping>();
            this.tblPartnerMappings1 = new HashSet<tblPartnerMapping>();
            this.tblPayments = new HashSet<tblPayment>();
            this.tblPayments1 = new HashSet<tblPayment>();
            this.tblPaymentTypes = new HashSet<tblPaymentType>();
            this.tblPaymentTypes1 = new HashSet<tblPaymentType>();
            this.tblPolicies = new HashSet<tblPolicy>();
            this.tblPolicies1 = new HashSet<tblPolicy>();
            this.tblPolicyCategories = new HashSet<tblPolicyCategory>();
            this.tblPolicyCategories1 = new HashSet<tblPolicyCategory>();
            this.tblPolicyInfoPayments = new HashSet<tblPolicyInfoPayment>();
            this.tblPolicyInfoPayments1 = new HashSet<tblPolicyInfoPayment>();
            this.tblPolicyInformationRecordings = new HashSet<tblPolicyInformationRecording>();
            this.tblPolicyInformationRecordings1 = new HashSet<tblPolicyInformationRecording>();
            this.tblPolicyRenewalHistories = new HashSet<tblPolicyRenewalHistory>();
            this.tblPolicyRenewalHistories1 = new HashSet<tblPolicyRenewalHistory>();
            this.tblQuotationDetailsInsCompanyHeaders = new HashSet<tblQuotationDetailsInsCompanyHeader>();
            this.tblQuotationDetailsInsCompanyHeaders1 = new HashSet<tblQuotationDetailsInsCompanyHeader>();
            this.tblQuotationDetailsInsCompanyLines = new HashSet<tblQuotationDetailsInsCompanyLine>();
            this.tblQuotationDetailsInsCompanyLines1 = new HashSet<tblQuotationDetailsInsCompanyLine>();
            this.tblQuotationDetailsInsCompanyScopes = new HashSet<tblQuotationDetailsInsCompanyScope>();
            this.tblQuotationDetailsInsCompanyScopes1 = new HashSet<tblQuotationDetailsInsCompanyScope>();
            this.tblQuotationLines = new HashSet<tblQuotationLine>();
            this.tblQuotationLines1 = new HashSet<tblQuotationLine>();
            this.tblQuotationRequestedInsCompanies = new HashSet<tblQuotationRequestedInsCompany>();
            this.tblQuotationRequestedInsCompanies1 = new HashSet<tblQuotationRequestedInsCompany>();
            this.tblRateCategories = new HashSet<tblRateCategory>();
            this.tblRateCategories1 = new HashSet<tblRateCategory>();
            this.tblRequiredDocuments = new HashSet<tblRequiredDocument>();
            this.tblRequiredDocuments1 = new HashSet<tblRequiredDocument>();
            this.tblSettings = new HashSet<tblSetting>();
            this.tblSettings1 = new HashSet<tblSetting>();
            this.tblTaxTypes = new HashSet<tblTaxType>();
            this.tblTaxTypes1 = new HashSet<tblTaxType>();
            this.tblTransactionTypes = new HashSet<tblTransactionType>();
            this.tblTransactionTypes1 = new HashSet<tblTransactionType>();
            this.tblUser1 = new HashSet<tblUser>();
            this.tblUser11 = new HashSet<tblUser>();
            this.tblClaimRecordings = new HashSet<tblClaimRecording>();
            this.tblClaimRecordings1 = new HashSet<tblClaimRecording>();
            this.tblPolicyCommisionPayment = new HashSet<tblPolicyCommisionPayment>();
            this.tblPolicyCommisionPayment1 = new HashSet<tblPolicyCommisionPayment>();
            this.tblChargeTypes = new HashSet<tblChargeType>();
            this.tblChargeTypes1 = new HashSet<tblChargeType>();
            this.tblClients = new HashSet<tblClient>();
            this.tblClients1 = new HashSet<tblClient>();
            this.tblPartners = new HashSet<tblPartner>();
            this.tblPartners1 = new HashSet<tblPartner>();
            this.tblClientRequestHeaders = new HashSet<tblClientRequestHeader>();
            this.tblQuotationHeaders = new HashSet<tblQuotationHeader>();
            this.tblQuotationHeaders1 = new HashSet<tblQuotationHeader>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public int AccessLevelType { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblAccessLevelType tblAccessLevelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAgent> tblAgents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAgent> tblAgents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBussinessUnit> tblBussinessUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBussinessUnit> tblBussinessUnits1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCauseOfLoss> tblCauseOfLosses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCauseOfLoss> tblCauseOfLosses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimPayment> tblClaimPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimPayment> tblClaimPayments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimPaymentMethod> tblClaimPaymentMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimPaymentMethod> tblClaimPaymentMethods1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimRecHistory> tblClaimRecHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimRecHistory> tblClaimRecHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimRecPendingDoc> tblClaimRecPendingDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimRecPendingDoc> tblClaimRecPendingDocs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimRejectReason> tblClaimRejectReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimRejectReason> tblClaimRejectReasons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimReOpenReason> tblClaimReOpenReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimReOpenReason> tblClaimReOpenReasons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClientProperty> tblClientProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClientProperty> tblClientProperties1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClientRequestInsSubClassScope> tblClientRequestInsSubClassScopes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClientRequestInsSubClassScope> tblClientRequestInsSubClassScopes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClientRequestLine> tblClientRequestLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClientRequestLine> tblClientRequestLines1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCommisionStructureHeader> tblCommisionStructureHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCommisionStructureHeader> tblCommisionStructureHeaders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCommisionStructureLine> tblCommisionStructureLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCommisionStructureLine> tblCommisionStructureLines1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCommisionType> tblCommisionTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCommisionType> tblCommisionTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCommonInsScope> tblCommonInsScopes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCommonInsScope> tblCommonInsScopes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompany> tblCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompany> tblCompanies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCoverNote> tblCoverNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCoverNote> tblCoverNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDebitNote> tblDebitNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDebitNote> tblDebitNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDesignation> tblDesignations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDesignation> tblDesignations1 { get; set; }
        public virtual tblDesignation tblDesignation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocCategory> tblDocCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocCategory> tblDocCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocument> tblDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocument> tblDocuments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployee> tblEmployees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInsClass> tblInsClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInsClass> tblInsClasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInsCompany> tblInsCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInsCompany> tblInsCompanies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInsSubClass> tblInsSubClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInsSubClass> tblInsSubClasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInternalPolicyNumSetup> tblInternalPolicyNumSetups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInternalPolicyNumSetup> tblInternalPolicyNumSetups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIntroducer> tblIntroducers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIntroducer> tblIntroducers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoadingType> tblLoadingTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoadingType> tblLoadingTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParentCompany> tblParentCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParentCompany> tblParentCompanies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPartnerMapping> tblPartnerMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPartnerMapping> tblPartnerMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment> tblPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment> tblPayments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaymentType> tblPaymentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaymentType> tblPaymentTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicy> tblPolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicy> tblPolicies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyCategory> tblPolicyCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyCategory> tblPolicyCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyInfoPayment> tblPolicyInfoPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyInfoPayment> tblPolicyInfoPayments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyInformationRecording> tblPolicyInformationRecordings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyInformationRecording> tblPolicyInformationRecordings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyRenewalHistory> tblPolicyRenewalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyRenewalHistory> tblPolicyRenewalHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationDetailsInsCompanyHeader> tblQuotationDetailsInsCompanyHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationDetailsInsCompanyHeader> tblQuotationDetailsInsCompanyHeaders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationDetailsInsCompanyLine> tblQuotationDetailsInsCompanyLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationDetailsInsCompanyLine> tblQuotationDetailsInsCompanyLines1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationDetailsInsCompanyScope> tblQuotationDetailsInsCompanyScopes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationDetailsInsCompanyScope> tblQuotationDetailsInsCompanyScopes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationLine> tblQuotationLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationLine> tblQuotationLines1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationRequestedInsCompany> tblQuotationRequestedInsCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationRequestedInsCompany> tblQuotationRequestedInsCompanies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRateCategory> tblRateCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRateCategory> tblRateCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequiredDocument> tblRequiredDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequiredDocument> tblRequiredDocuments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSetting> tblSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSetting> tblSettings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaxType> tblTaxTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaxType> tblTaxTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransactionType> tblTransactionTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransactionType> tblTransactionTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser> tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser> tblUser11 { get; set; }
        public virtual tblUser tblUser3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimRecording> tblClaimRecordings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimRecording> tblClaimRecordings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyCommisionPayment> tblPolicyCommisionPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyCommisionPayment> tblPolicyCommisionPayment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChargeType> tblChargeTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChargeType> tblChargeTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClient> tblClients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClient> tblClients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPartner> tblPartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPartner> tblPartners1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClientRequestHeader> tblClientRequestHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationHeader> tblQuotationHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationHeader> tblQuotationHeaders1 { get; set; }
    }
}
