//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test2
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AccountNo { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string Address { get; set; }
        public string Filler { get; set; }
        public string End { get; set; }
        public bool SaveStatus { get; set; }
        public string EnterUser { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> LineNo { get; set; }
        public string PostUser { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
